# yml文件要严格缩进，每次缩进空两个空格，不能用tab键缩进
server:
  # 服务段口号
  port: 8080
  # 服务名称
  servlet:
    context-path: /sm


spring:
  # 开启热部署
  devtools:
    restart:
      enabled: true
  # ----- 加载静态资源存放路径：js/css/图片/多媒体等 -----
  #resources:
  #  static-locations: classpath:/static/
  # 配置前端页面访问目录及页面后缀名
  mvc:
    # 静态资源映射路径
    static-path-pattern: /static/**
    view:
      prefix: classpath:/templates/
      suffix: .html
  # 配置数据源
  datasource:
    # jdbc:mysql://localhost:3306/smdb?serverTimezone=GMT%2B8&allowMultiQueries=true
    url: jdbc:mysql://localhost:3306/smdb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    # 数据库驱动
    driverClassName: com.mysql.cj.jdbc.Driver
    # 数据源类型，指定数据库连接池
    type: com.alibaba.druid.pool.DruidDataSource

# mybatis映射文件
mybatis:
  # 控制台自动打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # mapper.xml文件地址
  mapper-locations: classpath:mybatis/*Mapper.xml
  # 扫描持久化类，将类名作为包路径的别名，用于mapper.xml
  # 比如：com.st.model.Staff 该路径的别名就是 Staff
  type-aliases-package: com.qian.model

#logback日志
#日志可以分割，按时间分割、按文件大小分割
logging:
  # 日志输出级别，从低刀高为TRACE < DEBUG < INFO < WARN < ERROR < FATAL，默认是INFO级别
  level:
    com.st.controller.StaffController: INFO
    com.st.service.impl.StaffService: DEBUG
  # 日志文件输出路径
  path: D:\project\ideaLog
  # 日志文件名
  file: D:\project\ideaLog\shoppingmall.log
  # 日志输出匹配格式
  pattern:
    console: "%d - %msg%n"

# redis数据源
redis:
  # redis服务ip地址
  host: 127.0.0.1
  # 服务端口号
  port: 6379
  # 密码
  password:
  # 默认操作数据库索引DB0
  database: 0
  pool:
    # 连接池最大连接数（负值表示没有限制）
    max-active: 8
    # 连接池最大阻塞等待时间（负值表示没有限制）
    max-wait: 1
    # 最大空闲连接
    max-idle: 8
    # 最小空闲连接
    min-idle: 0
  # 连接超时时间（毫秒）
  timeout: 30000
  # 连接耗尽时是否阻塞, false报异常,ture阻塞直到超时, 默认true
  blockWhenExhausted: false

