# yml文件要严格缩进，每次缩进空两个空格，不能用tab键缩进
server:
  # 服务段口号
  port: 8080
  # 服务名称
  servlet:
    context-path: /sm


spring:
  # 开启热部署
  devtools:
    restart:
      enabled: true
  # ----- 加载静态资源存放路径：js/css/图片/多媒体等 -----
  #resources:
  #  static-locations: classpath:/static/
  # 配置前端页面访问目录及页面后缀名
  mvc:
    # 静态资源映射路径
    static-path-pattern: /static/**
    view:
      prefix: classpath:/templates/
      suffix: .html
  # 配置数据源
  datasource:
    # jdbc:mysql://localhost:3306/mydb?serverTimezone=GMT%2B8&allowMultiQueries=true
    url: jdbc:mysql://localhost:3306/smdb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    # 数据库驱动
    driverClassName: com.mysql.cj.jdbc.Driver
    # 数据源类型，指定数据库连接池
    type: com.alibaba.druid.pool.DruidDataSource

# mybatis映射文件
mybatis:
  # 控制台自动打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # mapper.xml文件地址
  mapper-locations: classpath:mybatis/*Mapper.xml
  # 扫描持久化类，将类名作为包路径的别名，用于mapper.xml
  # 比如：com.st.model.Staff 该路径的别名就是 Staff
  type-aliases-package: com.qian.model
